#!/usr/bin/env bash
# It sets a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_replacement="server_name _;\n\tadd_header X-Served-By $HOSTNAME;\n\trewrite ^\/redirect_me https:\/\/github.com\/Anasoud1 permanent;"
sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
